# vim:fileencoding=utf-8:foldmethod=marker

# : Manager {{{

[manager]
cwd = { fg = "#83a598" }

# Hovered
hovered = { fg = "#282828", bg = "#83a598" }
preview_hovered = { underline = true }

# Find
find_keyword = { fg = "#b8bb26", italic = true }
find_position = { fg = "#fe8019", bg = "reset", italic = true }

# Marker
marker_selected = { fg = "#b8bb26", bg = "#b8bb26" }
marker_copied = { fg = "#b8bb26", bg = "#b8bb26" }
marker_cut = { fg = "#fb4934", bg = "#fb4934" }

# Tab
tab_active = { fg = "#282828", bg = "#504945" }
tab_inactive = { fg = "#a89984", bg = "#3c3836" }
tab_width = 1

# Border
border_symbol = "│"
border_style = { fg = "#665c54" }

# Highlighting
syntect_theme = "~/.config/yazi/Gruvbox-Material-Dark.tmTheme"

# : }}}


# : Status {{{

[status]
separator_open = ""
separator_close = ""
separator_style = { fg = "#3c3836", bg = "#3c3836" }

# Mode
mode_normal = { fg = "#282828", bg = "#A89984", bold = true }
mode_select = { fg = "#282828", bg = "#b8bb26", bold = true }
mode_unset = { fg = "#282828", bg = "#d3869b", bold = true }

# Progress
progress_label = { fg = "#ebdbb2", bold = true }
progress_normal = { fg = "#504945", bg = "#3c3836" }
progress_error = { fg = "#fb4934", bg = "#3c3836" }

# Permissions
permissions_t = { fg = "#504945" }
permissions_r = { fg = "#b8bb26" }
permissions_w = { fg = "#fb4934" }
permissions_x = { fg = "#b8bb26" }
permissions_s = { fg = "#665c54" }

# : }}}


# : Input {{{

[input]
border = { fg = "#bdae93" }
title = {}
value = {}
selected = { reversed = true }

# : }}}


# : Select {{{

[select]
border = { fg = "#504945" }
active = { fg = "#fe8019" }
inactive = {}

# : }}}


# : Tasks {{{

[tasks]
border = { fg = "#504945" }
title = {}
hovered = { underline = true }

# : }}}


# : Which {{{

[which]
mask = { bg = "#3c3836" }
cand = { fg = "#83a598" }
rest = { fg = "#928374" }
desc = { fg = "#fe8019" }
separator = "  "
separator_style = { fg = "#504945" }

# : }}}


# : Help {{{

[help]
on = { fg = "#fe8019" }
exec = { fg = "#83a598" }
desc = { fg = "#928374" }
hovered = { bg = "#504945", bold = true }
footer = { fg = "#3c3836", bg = "#a89984" }

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
  # Images
  { mime = "image/*", fg = "#83a598" },

  # Videos
  { mime = "video/*", fg = "#b8bb26" },
  { mime = "audio/*", fg = "#b8bb26" },

  # Archives
  { mime = "application/zip", fg = "#fe8019" },
  { mime = "application/gzip", fg = "#fe8019" },
  { mime = "application/x-tar", fg = "#fe8019" },
  { mime = "application/x-bzip", fg = "#fe8019" },
  { mime = "application/x-bzip2", fg = "#fe8019" },
  { mime = "application/x-7z-compressed", fg = "#fe8019" },
  { mime = "application/x-rar", fg = "#fe8019" },

  { name = "*.ko", bold = true },
  { name = "*.ps", bold = true },
  { name = "*.rm", bold = true },
  { name = "*.so", bold = true },
  { name = "*FAQ", bold = true },
  { name = "*.avi", bold = true },
  { name = "*.bat", bold = true },
  { name = "*.bin", bold = true },
  { name = "*.cfg" },
  { name = "*.com", bold = true },
  { name = "*.dll", bold = true },
  { name = "*.dmg", bold = true },
  { name = "*.doc", bold = true },
  { name = "*.exe", bold = true },
  { name = "*.flv", bold = true },
  { name = "*.ics", bold = true },
  { name = "*.img", bold = true },
  { name = "*.iso", bold = true },
  { name = "*.kex", bold = true },
  { name = "*.m4v", bold = true },
  { name = "*.mkv", bold = true },
  { name = "*.mov", bold = true },
  { name = "*.mp4", bold = true },
  { name = "*.mpg", bold = true },
  { name = "*.odp", bold = true },
  { name = "*.ods", bold = true },
  { name = "*.odt", bold = true },
  { name = "*.ogv", bold = true },
  { name = "*.pdf", bold = true },
  { name = "*.pps", bold = true },
  { name = "*.ppt", bold = true },
  { name = "*.rtf", bold = true },
  { name = "*.swf", bold = true },
  { name = "*.sxi", bold = true },
  { name = "*.sxw", bold = true },
  { name = "*.vcd", bold = true },
  { name = "*.vob", bold = true },
  { name = "*.wmv", bold = true },
  { name = "*.xlr", bold = true },
  { name = "*.xls", bold = true },
  { name = "*.docx", bold = true },
  { name = "*.epub", bold = true },
  { name = "*.h264", bold = true },
  { name = "*.mpeg", bold = true },
  { name = "*.pptx", bold = true },
  { name = "*.webm", bold = true },
  { name = "*.xlsx", bold = true },
  { name = "*.dylib", bold = true },
  { name = "*.toast", bold = true },
  { name = "*LEGACY", bold = true },
  { name = "*NOTICE", bold = true },
  { name = "*README", bold = true },
  { name = "*INSTALL", bold = true },
  { name = "*VERSION", bold = true },
  { name = "*CHANGELOG", bold = true },
  { name = "*README.md", bold = true },
  { name = "*INSTALL.md", bold = true },
  { name = "*README.txt", bold = true },
  { name = "*INSTALL.txt", bold = true },
  { name = "*CHANGELOG.md", bold = true },
  { name = "*CONTRIBUTING", bold = true },
  { name = "*CONTRIBUTORS", bold = true },
  { name = "*CHANGELOG.txt", bold = true },
  { name = "*CODE_OF_CONDUCT", bold = true },
  { name = "*CONTRIBUTING.md", bold = true },
  { name = "*CONTRIBUTORS.md", bold = true },
  { name = "*CONTRIBUTING.txt", bold = true },
  { name = "*CONTRIBUTORS.txt", bold = true },
  { name = "*CODE_OF_CONDUCT.md", bold = true },
  { name = "*CODE_OF_CONDUCT.txt", bold = true },

  # Fallback
  { name = "*", fg = "#a89984" },
  { name = "*/", fg = "#83a598" },

]

# : }}}
